// build info - autogenerated do not manually edit
//
// Build date & time stamp for 2015:02:11 23:09:40
//

#ifndef BUILD_INFO_H_
#define BUILD_INFO_H_

// Provide an integer representation of the time in human-readable form
#define __BI__TIMESTAMP_INT 230940

// Provide a 3 8-bit representation of the time in human-readable form
#define __BI__TIMESTAMP_INT8_HR 23
#define __BI__TIMESTAMP_INT8_MI 9
#define __BI__TIMESTAMP_INT8_SE 40

// Provide a 6 byte string representation of the time
#define __BI__TIMESTAMP_STR "230940"


// Provide an integer representation of the date in human-readable form
#define __BI__DATESTAMP_INT 150211

// Provide a 3 8-bit representation of the date in human-readable form
#define __BI__DATESTAMP_INT8_YR 15
#define __BI__DATESTAMP_INT8_MO 2
#define __BI__DATESTAMP_INT8_DA 11

// Provide a 6 byte string representation of the date
#define __BI__DATESTAMP_STR "150211"


#endif /* BUILD_INFO_H_ */

