// build info - autogenerated do not manually edit
//
// Build date & time stamp for 2015:02:02 00:53:40
//

#ifndef BUILD_INFO_H_
#define BUILD_INFO_H_

// Provide an integer representation of the time in human-readable form
#define __BI__TIMESTAMP_INT 5340

// Provide a 3 8-bit representation of the time in human-readable form
#define __BI__TIMESTAMP_INT8_HR 0
#define __BI__TIMESTAMP_INT8_MI 53
#define __BI__TIMESTAMP_INT8_SE 40

// Provide a 6 byte string representation of the time
#define __BI__TIMESTAMP_STR "005340"


// Provide an integer representation of the date in human-readable form
#define __BI__DATESTAMP_INT 150202

// Provide a 3 8-bit representation of the date in human-readable form
#define __BI__DATESTAMP_INT8_YR 15
#define __BI__DATESTAMP_INT8_MO 2
#define __BI__DATESTAMP_INT8_DA 2

// Provide a 6 byte string representation of the date
#define __BI__DATESTAMP_STR "150202"


#endif /* BUILD_INFO_H_ */

